[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
